import { h, Component } from 'preact';
import Message from './MessageComponent';

export default class HomeComponent extends Component {
    render(props) {
        return (
            <section className="component-home">
                <h3>Recover your Bitcoins</h3>
                <Message
                    header="Reading of accounts failed."
                    error={ props.error }
                    hideError={ props.hideError } />
                <fieldset>
                    <p>This tool can help you recover your Bitcoins which were sent to Bitcoin Cash (BCash) addresses generated by your TREZOR.</p>
                    <p>Your BTC will be recovered to your Bitcoin wallet in TREZOR.</p>
                    <div>
                        <button onClick={ () => { props.click() } } disabled={ !props.block }>Connect with TREZOR</button>
                    </div>
                </fieldset>
            </section>
        );
    }
}